### PR TITLE
Update IP cores and u-boot patches to Vivado 2018.3

### PR DESCRIPTION
**Pull request by vnegnev**
Bumped version numbers of Xilinx IP cores; TCL build scripts work.
Obsolete u-boot and linux patches removed.
Adapted latest 2018.3 Makefile and patches from Pavel Demin's red-pitaya-notes repo.
Tweaked devicetree.patch to work with ocra_mri hardware.
Boots with pre-compiled Debian image; haven't yet tested any FPGA functionality (all Red Pitaya LEDs come on, which seems like a bad sign)

### CODE REVIEW

**Comment by vnegnev** [comment]
Maybe it makes more sense to make a new branch in the ocra repo for Vivado 2018.3 and commit there, rather than to master.

**Comment by twitzelbos** [comment]
Whatever you think is best at this point.

Thomas

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by vnegnev** [comment]
I guess a new branch is best until we've tested the FPGA functionality and everyone's upgraded their Vivados. I just noticed the meta-openmri repo - I'll play around with that and try to test out the FPGA bitstream during the week.

**Comment by mriphysicist** [comment]
I created a new branch to host your changes.  Will you change your pull request to branch viv2018.3_updates and I will accept it?

Thanks,
Danny

**Comment by mriphysicist** [comment]
Hi vnegnev,

I put your changes into a new branch.  I am closing this pull request because because your changes are now in the branch viv2018.3_updates.

Thanks,
Danny

**Pull request closed without merging**
