### PR TITLE
chore/cleanup

### PR DESCRIPTION
**Pull request by marcman86**
Removed hex files. Hex files are automatically generated by assembler when loading a sequence. Also removed old unused icons.
Add a gitignore to prevent hex files to be added to the repo.

### CODE REVIEW

**Comment by marcman86** [comment]
done with this first cleanup. Deleted outdated code from server and added comments.

Ready for review

**Review by dcstraney — COMMENTED** [review]
Can't speak for every single change in relax_server_dev.c but a lot of that file's changes and all the other ones look pretty safe.

In the .gitignores though, not familiar with that part of the project structure but is it worth just doing a *_hex.txt to cover everything as well as future renamings etc.?

**Comment by marcman86** [comment]
> Can't speak for every single change in relax_server_dev.c but a lot of that file's changes and all the other ones look pretty safe.
> 
> In the .gitignores though, not familiar with that part of the project structure but is it worth just doing a *_hex.txt to cover everything as well as future renamings etc.?

Did that. Hope this works :-)

**Review by dcstraney — DISMISSED** [review]
Yeah can definitely use wildcards in .gitignore, it's very useful.  For example, an excerpt from a gitignore for a different repo I'm on:

# --- backup and output directories ---
# (To filter out altium-stuff, I propose being explicit from a level, not global)
History/
Project Logs for */
logs/
Project Outputs for */
output/
Outputs/
Manufacturing/
*.TxtPreview

**Review by twitzelbos — APPROVED** [review]

**Pull request merged**
